-- Required for the Workshop Media Bot (Task 5/6): a second, independent
-- Telegram bot that lets workshop staff save media from an internal
-- group to a specific vehicle, review it in a manager group, and
-- optionally forward it to the customer.
--
-- Purely additive: two new tables, no existing tables/columns touched.
--
-- Run this once in the Supabase SQL editor (or via `psql`).
--
-- Until this is applied, the workshop bot (if WORKSHOP_BOT_TOKEN is even
-- set — it's off by default) will reply with a graceful "something went
-- wrong" message on /save rather than crash, but the feature won't
-- actually work.

-- Maps one workshop's internal Telegram group (where mechanics/staff
-- post freely) to the company it belongs to and to the manager group
-- that reviews saved media. One company could have more than one
-- workshop group in principle, so this is not unique on company_id —
-- only on workshop_group_id (a single Telegram group can only ever
-- belong to one company/workshop).
create table if not exists workshop_telegram_groups (
    id bigint generated by default as identity primary key,
    company_id bigint not null references companies(id) on delete cascade,
    workshop_group_id bigint not null,
    manager_group_id bigint not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    unique (workshop_group_id)
);

-- One row per /save action. source_* identifies the original message in
-- the workshop group; manager_* identifies the bot's copy of it in the
-- manager group (what "Send to customer" actually re-sends). The unique
-- constraint on (source_chat_id, source_message_id) is what lets /save
-- detect "this exact message was already saved" instead of creating a
-- duplicate entry and re-spamming the manager group.
create table if not exists saved_media (
    id bigint generated by default as identity primary key,
    company_id bigint not null references companies(id) on delete cascade,
    vehicle_id bigint not null references cars(id) on delete cascade,
    source_chat_id bigint not null,
    source_message_id bigint not null,
    manager_chat_id bigint not null,
    manager_message_id bigint,
    saved_by_telegram_user_id bigint not null,
    saved_by_name text,
    saved_at timestamptz not null default now(),
    sent_to_customer boolean not null default false,
    sent_at timestamptz null,
    sent_by_telegram_user_id bigint null,
    unique (source_chat_id, source_message_id)
);

create index if not exists saved_media_company_id_idx on saved_media (company_id);
create index if not exists saved_media_vehicle_id_idx on saved_media (vehicle_id);

-- No management UI exists yet for workshop_telegram_groups (out of scope
-- for the MVP) — insert rows directly, e.g.:
--
-- insert into workshop_telegram_groups (company_id, workshop_group_id, manager_group_id)
-- values (1, -1001234567890, -1009876543210);
--
-- Group IDs: add the bot to both Telegram groups, then send any message
-- and check the bot's getUpdates/logs for that chat's numeric id
-- (supergroup ids are negative, e.g. -100xxxxxxxxxx).
