-- Supports the owner-driven "Connect Workshop Group" / "Connect Manager
-- Group" flow (admin.js's new /admin/telegram-setup routes, workshopBot.js's
-- new /start, callback, and my_chat_member handlers).
--
-- Purely additive except for one constraint relaxation — no existing rows
-- modified, no existing columns removed.

-- Links a web admin account to a Telegram account. Set once, via a
-- one-time token (see telegram_connect_tokens below), then used to
-- authorize every later group-connection action for that admin's
-- company — never trusted from a client-supplied value.
alter table admin_accounts add column if not exists telegram_id bigint;

-- A Telegram account may only ever be linked to ONE admin_account — this
-- is a 1:1 bridge, not the many-to-many model used for customers
-- (companies.telegram_id per migrations/007 is a different relationship:
-- one real person can be a CUSTOMER of many companies, but each company's
-- OWNER admin login is still exactly one person). Partial index (WHERE
-- telegram_id is not null) so unlinked admins (the default/existing state
-- for every admin today, including companies 9 and 58) never collide.
create unique index if not exists admin_accounts_telegram_id_key
    on admin_accounts (telegram_id) where telegram_id is not null;

-- Single-use, short-lived bridge tokens. Generated by an authenticated
-- admin panel session (so admin_id/company_id are always trustworthy,
-- never client-supplied), consumed exactly once by the Workshop Bot's
-- /start handler to set admin_accounts.telegram_id above.
create table if not exists telegram_connect_tokens (
    id bigint generated by default as identity primary key,
    token text not null unique,
    admin_id bigint not null references admin_accounts(id) on delete cascade,
    company_id bigint not null references companies(id) on delete cascade,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    consumed_at timestamptz null
);

create index if not exists telegram_connect_tokens_token_idx on telegram_connect_tokens (token);

-- Relaxed so a Workshop Group can be connected before a Manager Group
-- exists for that company (the required ordering — Workshop first,
-- Manager second). Existing rows (companies 9 and 58) already have a
-- non-null value here, so this changes nothing for them; it only
-- permits a NEW row to be inserted with manager_group_id left null
-- until the Manager Group connection step fills it in.
alter table workshop_telegram_groups alter column manager_group_id drop not null;
